const companies = ["Google", "Microsoft", "Amazon", "Salesforce", "HubSpot", "Shopify", "Stripe", "Notion", "Webflow", "Deloitte"];

export function TrustedCompaniesSection() {
  return <section aria-labelledby="trusted-heading" className="overflow-hidden border-y border-border/40 py-12 md:py-16"><div className="mx-auto max-w-7xl px-6"><p className="text-center text-xs font-medium uppercase tracking-[0.28em] text-muted-foreground">Trusted by fast-growing global companies</p><h2 id="trusted-heading" className="sr-only">Trusted by fast-growing global companies</h2></div><div className="mt-10 flex w-max animate-[ticker-scroll_28s_linear_infinite] gap-4 hover:[animation-play-state:paused]">{[...companies, ...companies].map((company, index) => <div key={`${company}-${index}`} className="flex h-16 min-w-[170px] items-center justify-center rounded-2xl border border-border/60 bg-card/30 px-8 text-lg font-semibold tracking-tight text-foreground/60 grayscale">{company}</div>)}</div></section>;
}

export function TestimonialsSection() {
  const testimonials = [{ quote: "Emporri gave our team back the hours we were losing to repetitive calls.", name: "Maya Chen", role: "COO, Northstar Health" }, { quote: "The voice quality feels genuinely human, and our customers noticed immediately.", name: "James Okafor", role: "Founder, Atlas Commerce" }, { quote: "We launched in days and saw a measurable lift in booked appointments.", name: "Sofia Martin", role: "Growth Lead, Lumen" }];
  return <section id="testimonials" className="px-6 py-16 md:py-20"><div className="mx-auto max-w-7xl"><div className="mb-10 max-w-2xl"><p className="text-xs font-medium uppercase tracking-[0.28em] text-primary">Customer stories</p><h2 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">Built for teams that move fast.</h2></div><div className="grid gap-5 md:grid-cols-3">{testimonials.map((item) => <figure key={item.name} className="rounded-3xl border border-border/60 bg-card/30 p-7"><div className="text-primary" aria-label="5 out of 5 stars">★★★★★</div><blockquote className="mt-6 text-lg leading-relaxed text-foreground">“{item.quote}”</blockquote><figcaption className="mt-8 text-sm text-muted-foreground"><span className="block font-semibold text-foreground">{item.name}</span>{item.role}</figcaption></figure>)}</div></div></section>;
}

export function BlogSection() {
  const posts = [{ title: "What is an AI receptionist?", excerpt: "A practical guide to answering every call without adding another shift.", date: "May 14, 2026" }, { title: "The economics of never missing a lead", excerpt: "How fast-growing teams turn response time into a competitive advantage.", date: "Apr 28, 2026" }, { title: "Designing a voice agent customers trust", excerpt: "The conversation principles behind helpful, natural AI experiences.", date: "Apr 09, 2026" }];
  return <section id="blog" aria-labelledby="blog-heading" className="px-6 py-16 md:py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-medium uppercase tracking-[0.28em] text-primary">Emporri journal</p><h2 id="blog-heading" className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">Ideas for better conversations.</h2></div><a href="/admin" className="text-sm text-muted-foreground underline-offset-4 hover:text-foreground hover:underline">Admin access</a></div><div className="mt-10 grid gap-5 md:grid-cols-3">{posts.map((post) => <article key={post.title} className="rounded-3xl border border-border/60 bg-card/30 p-7 transition-colors hover:border-primary/40"><p className="text-xs text-muted-foreground">{post.date}</p><h3 className="mt-5 text-xl font-semibold">{post.title}</h3><p className="mt-3 leading-relaxed text-muted-foreground">{post.excerpt}</p><a href="#" className="mt-7 inline-block text-sm font-medium text-primary">Read article →</a></article>)}</div></div></section>;
}

export function RoiCalculator() {
  return <section id="roi" className="px-6 py-16 md:py-20"><div className="mx-auto grid max-w-6xl gap-8 rounded-3xl border border-primary/20 bg-card/30 p-8 md:grid-cols-[1fr_auto] md:items-center md:p-12"><div><p className="text-xs font-medium uppercase tracking-[0.28em] text-primary">ROI calculator</p><h2 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">Turn every missed call into a growth opportunity.</h2><p className="mt-4 max-w-xl leading-relaxed text-muted-foreground">Traditional receptionist coverage starts at $4,500/month. Emporri helps your team capture demand around the clock with a fraction of the overhead.</p></div><div className="rounded-2xl border border-border/60 bg-background/50 p-7 text-center"><p className="text-sm text-muted-foreground">Typical monthly saving</p><p className="mt-2 text-5xl font-bold text-primary">$3,600+</p><p className="mt-2 text-xs text-muted-foreground">based on 30 calls/day</p><a href="#live-demo" className="mt-6 inline-flex rounded-full bg-primary px-6 py-3 text-sm font-medium text-primary-foreground">Calculate your ROI</a></div></div></section>;
}
